export let videos = [
    { 
                id: 1,
                inicio: "todo",
                categoria:"music",
                video: "../caratula/destripando1.webp",
                usuario:"../caratula/destripando1.webp",
                icono:"../iconos/destripando.jpg",
                nombre: "Hermes | Destripando la Historia",
                canal: "Pascu y Rodri",
                vistas: "9.729.396 visualizaciones",
                fecha:"22 dic 2021",

            },
            {
                id: 2,
                inicio: "todo",
                categoria:"music",
                video: "../caratula/destripando2.webp",
                usuario:"../caratula/destripando2.webp",
                icono:"../iconos/destripando.jpg",
                nombre: "Afrodita | Destripando la Historia",
                canal: "Pascu y Rodri",
                vistas: "34.970.014 isualizaciones",
                fecha:"20 oct 2021",

            },
            {
                id: 3,
                inicio: "todo",
                categoria:"music",
                video: "../caratula/destripando3.webp",
                usuario:"../caratula/destripando3.webp",
                icono:"../iconos/destripando.jpg",
                nombre: "Gilgamesh | Destripando la Historia",
                canal: "Pascu y Rodri",
                vistas: "14.769.615 visualizaciones",
                fecha:"28 jul 2021",

            },
            {
                id: 4,
                inicio: "todo",
                categoria:"music",
                video: "../Videos/y2mate.com - Ares  Destripando la Historia_v720P.mp4",
                usuario:"../caratula/destripando4.webp",
                icono:"../iconos/destripando.jpg",
                nombre: "Ares | Destripando la Historia",
                canal: "Pascu y Rodri",
                vistas: "23.746.070 visualizaciones",
                fecha:"12 may 2021",

            },
            {
                id: 5,
                inicio: "todo",
                categoria:"music",
                video: "../caratula/destripando5.webp",
                usuario:"../caratula/destripando5.webp",
                icono:"../iconos/destripando.jpg",
                nombre: "Hércules HD | Destripando la Historia",
                canal: "Pascu y Rodri",
                vistas: "21.510.403 visualizaciones",
                fecha:"16 dic 2020",

            },
            {
                id: 6,
                inicio: "todo",
                categoria:"music",
                video: "../caratula/destripando6.webp",
                usuario:"../caratula/destripando6.webp",
                icono:"../iconos/destripando.jpg",
                nombre: "Freyja | Destripando la Historia",
                canal: "Pascu y Rodri",
                vistas: "17.525.555 visualizaciones",
                fecha:"4 nov 2020",

            },
            {
                id: 7,
                inicio: "todo",
                categoria:"music",
                video: "../caratula/destripando7.webp",
                usuario:"../caratula/destripando7.webp",
                icono:"../iconos/destripando.jpg",
                nombre: "Odín | Destripando la Historia",
                canal: "Pascu y Rodri",
                vistas: "24.739.268 visualizaciones",
                fecha:"16 sept 2020",

            },
            {
                id: 8,
                inicio: "todo",
                categoria:"music",
                video: "../Videos/y2mate.com - Hera  Destripando la Historia_720p.mp4",
                usuario:"../caratula/destripando8.webp",
                icono:"../iconos/destripando.jpg",
                nombre: "Hera | Destripando la Historia",
                canal: "Pascu y Rodri",
                vistas: "41.421.245 visualizaciones",
                fecha:"15 jul 2020",

            },
            {
                id: 9,
                inicio: "todo",
                categoria:"music",
                video: "../caratula/destripando9.webp",
                usuario:"../caratula/destripando9.webp",
                icono:"../iconos/destripando.jpg",
                nombre: "Hestia | Destripando la Historia",
                canal: "Pascu y Rodri",
                vistas: "35.679.367 visualizaciones",
                fecha:"13 may 2020",

            },
            {
                id: 10,
                inicio: "todo",
                categoria:"music",
                video: "../Videos/y2mate.com - DEMÉTER  Destripando la Historia_v720P.mp4",
                usuario:"../caratula/destripando10.webp",
                icono:"../iconos/destripando.jpg",
                nombre: "DEMÉTER | Destripando la Historia",
                canal: "Pascu y Rodri",
                vistas: "34.062.123 visualizaciones",
                fecha:"11 mar 2020",

            },
            {
                id: 11,
                inicio: "todo",
                categoria:"diseño UX",
                video: "../caratula/charli1.webp",
                usuario:"../caratula/charli1.webp",
                icono:"../iconos/charli.jpg",
                nombre: "Work From Home Desk Setup As A UX Designer",
                canal: "Charli Cheung",
                vistas: "3831 visualizaciones",
                fecha:"11 abril 2022",
            },
            {
                id: 12,
                inicio: "todo",
                categoria:"diseño UX",
                video: "../Videos/MacBook Pro 14’’ 2021 M1 Unboxing & Set Up As A UX Designer.mp4",
                usuario:"../caratula/charli2.webp",
                icono:"../iconos/charli.jpg",
                nombre: "MacBook Pro 14’’ 2021 M1 Unboxing & Set Up As A UX Designer",
                canal: "Charli Cheung",
                vistas: "3850 visualizaciones",
                fecha:"05 marzo 2022",
            },
            {
                id: 13,
                inicio: "todo",
                categoria:"diseño UX",
                video: "../caratula/charli3.webp",
                usuario:"../caratula/charli3.webp",
                icono:"../iconos/charli.jpg",
                nombre: "Week In My Life As A Senior UX Designer | Design Workshops",
                canal: "Charli Cheung",
                vistas: "2923 visualizaciones",
                fecha:" 25 febrero 2022",
            },
            {
                id: 14,
                inicio: "todo",
                categoria:"diseño UX",
                video: "../caratula/charli4.webp",
                usuario:"../caratula/charli4.webp",
                icono:"../iconos/charli.jpg",
                nombre: "Day In My Life As A UX Designer | Goals for 2022",
                canal: "Charli Cheung",
                vistas: "4726 visualizaciones",
                fecha:"20 enero 2022",
            },
            {
                id: 15,
                inicio: "todo",
                categoria:"diseño UX",
                video: "../caratula/charli5.webp",
                usuario:"../caratula/charli5.webp",
                icono:"../iconos/charli.jpg",
                nombre: "A Week In The Life Of A UX Designer",
                canal: "Charli Cheung",
                vistas: "92.014 visualizaciones",
                fecha:"2 enero 2022",
            },
            {
                id: 16,
                inicio: "todo",
                categoria:"diseño UX",
                video: "../caratula/charli6.webp",
                usuario:"../caratula/charli6.webp",
                icono:"../iconos/charli.jpg",
                nombre: "Self Care Vlog | Christmas tree, baking, video games + more!",
                canal: "Charli Cheung",
                vistas: "465 visualizaciones",
                fecha:"26 dic 2021",
            },
            {
                id: 17,
                inicio: "todo",
                categoria:"diseño UX",
                video: "../caratula/charli7.webp",
                usuario:"../caratula/charli7.webp",
                icono:"../iconos/charli.jpg",
                nombre: "A Productive Week in my Life | UX design, vector illustration, Christmas tree shopping + more!",
                canal: "Charli Cheung",
                vistas: "1300 visualizaciones",
                fecha:"10 dic 2021",
            },
            {
                id: 18,
                inicio: "todo",
                categoria:"diseño UX",
                video: "../caratula/charli8.webp",
                usuario:"../caratula/charli8.webp",
                icono:"../iconos/charli.jpg",
                nombre: "How to get freelance UX design jobs (what worked + what didn't)",
                canal: "Charli Cheung",
                vistas: "3185 visualizaciones",
                fecha:"20 nov 2021",
            },
            {
                id: 19,
                inicio: "todo",
                categoria:"diseño UX",
                video: "../caratula/charli9.webp",
                usuario:"../caratula/charli9.webp",
                icono:"../iconos/charli.jpg",
                nombre: "Resetting from burn out | Vlog",
                canal: "Charli Cheung",
                vistas: "734 visualizaciones",
                fecha:"6 nov 2021",
            },
            {
                id: 20,
                inicio: "todo",
                categoria:"diseño UX",
                video: "../caratula/charli10.webp",
                usuario:"../caratula/charli10.webp",
                icono:"../iconos/charli.jpg",
                nombre: "Q&A | Uni Regrets + Learning UX + the WORST thing about being a UX Designer",
                canal: "Charli Cheung",
                vistas: "1384 visualizaciones",
                fecha:"30 oct 2022",
            },
            {
                id: 21,
                inicio: "todo",
                categoria:"programacion",
                video: "../caratula/dalto1.webp",
                usuario:"../caratula/dalto1.webp",
                icono:"../iconos/soydalto.jpg",
                nombre: "5 TRUCOS de PROGRAMADORES que CUALQUIERA puede HACER",
                canal: "Soy Dalto",
                vistas: "48.541 visualizaciones",
                fecha:"17 abr 2022",
            },
            {
                id: 22,
                inicio: "todo",
                categoria:"programacion",
                video: "../caratula/dalto2.webp",
                usuario:"../caratula/dalto2.webp",
                icono:"../iconos/soydalto.jpg",
                nombre: "Como CREAR un JUEGO desde CERO",
                canal: "Soy Dalto",
                vistas: "72.611 visualizaciones",
                fecha:"10 mar 2022",
            },
            {
                id: 23,
                inicio: "todo",
                categoria:"programacion",
                video: "../caratula/dalto3.webp",
                usuario:"../caratula/dalto3.webp",
                icono:"../iconos/soydalto.jpg",
                nombre: "Como GANAR 2000 USD en UN AÑO con la PROGRAMACIÓN comenzando HOY",
                canal: "Soy Dalto",
                vistas: "139.792 visualizaciones",
                fecha:"17 feb 2022",
            },
            {
                id: 24,
                inicio: "todo",
                categoria:"programacion",
                video: "../caratula/dalto4.webp",
                usuario:"../caratula/dalto4.webp",
                icono:"../iconos/soydalto.jpg",
                nombre: "Como CREAR un NFT desde CERO",
                canal: "Soy Dalto",
                vistas: "82.763 visualizaciones",
                fecha:"15 ene 2022",
            },
            {
                id: 25,
                inicio: "todo",
                categoria:"programacion",
                video: "../caratula/dalto5.webp",
                usuario:"../caratula/dalto5.webp",
                icono:"../iconos/soydalto.jpg",
                nombre: "¿Cuanto GANA un PROGRAMADOR en ARGENTINA?",
                canal: "Soy Dalto",
                vistas: "304.352 visualizaciones",
                fecha:"1 dic 2021",
            },
            {
                id: 26,
                inicio: "todo",
                categoria:"programacion",
                video: "../Videos/DALTO ACTIVA WINDOWS.mp4",
                usuario:"../caratula/dalto6.webp",
                icono:"../iconos/soydalto.jpg",
                nombre: "DALTO ACTIVA WINDOWS",
                canal: "Soy Dalto",
                vistas: "98.739 visualizaciones",
                fecha:"23 nov 2021",
            },
            {
                id: 27,
                inicio: "todo",
                categoria:"programacion",
                video: "../caratula/dalto7.webp",
                usuario:"../caratula/dalto7.webp",
                icono:"../iconos/soydalto.jpg",
                nombre: "NO HAGAS UN SITIO WEB SIN VER ESTE VIDEO",
                canal: "Soy Dalto",
                vistas: "59.197 visualizaciones",
                fecha:"16 sept 2021",
            },
            {
                id: 28,
                inicio: "todo",
                categoria:"programacion",
                video: "../caratula/dalto8.webp",
                usuario:"../caratula/dalto8.webp",
                icono:"../iconos/soydalto.jpg",
                nombre: "ANALIZO EL PROYECTO ARGENTINA PROGRAMA - ¿VALE LA PENA?",
                canal: "Soy Dalto",
                vistas: "152.865 visualizaciones",
                fecha:"9 sept 2021",
            },
            {
                id: 29,
                inicio: "todo",
                categoria:"programacion",
                video: "../caratula/dalto9.webp",
                usuario:"../caratula/dalto9.webp",
                icono:"../iconos/soydalto.jpg",
                nombre: "¿SE NECESITA INGLÉS PARA SER PROGRAMADOR? - Q&A",
                canal: "Soy Dalto",
                vistas: "68.822 visualizaciones",
                fecha:"15 ago 2021",
            },
            {
                id: 30,
                inicio: "todo",
                categoria:"programacion",
                video: "../caratula/dalto10.webp",
                usuario:"../caratula/dalto10.webp",
                icono:"../iconos/soydalto.jpg",
                nombre: "EL VERDADERO MOTIVO PARA APRENDER A PROGRAMAR",
                canal: "Soy Dalto",
                vistas: "111.953 visualizaciones",
                fecha:"8 ago 2021",
            },
]